### ISSUE TITLE
오디오 재생시간 맨 앞/뒤로 건너뛰기 기능 구현

### ISSUE THREAD

**Issue by Jeongeun-Choi** [boostcamp-2020/Project14-A-Web-Audio-Editor#24]
## 💁 설명

맨 앞/뒤로 가기 버튼을 누르면 재생 시간의 맨 앞/뒤로 건너뛰는 기능 구현

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] 버튼을 클릭하면 marker가 재생구간의 start/end 지점으로 이동하며 해당 위치에서 재생된다.

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

**Comment by pieisland** [comment]
loop가 아닐 때는 맨 뒤로가서 멈추고, loop일 때는 맨 뒤로 갔다가 맨 앞으로 가기.

**Comment by pieisland** [comment]
audiomass에서는 loop상태에서 맨 뒤로 가도 loop에 제약 없이 그냥 맨 뒤로 감.
맨 앞도 마찬가지로 loop가 해제되는 듯.

**Comment by pieisland** [comment]
현재 loop와 관계없이 맨 앞, 맨 뒤로 이동 중.
